import React from 'react';
import { useState } from 'react';
import { Button, Center, Container, Text, Card, Paper, FloatingIndicator, Tabs, Modal, Indicator, SimpleGrid } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';

interface Product {
  title: string
  description: string
}

interface Subject {
  title: string
  description: string
  products: Product[]
}

const subjects:Subject[] = [
  {
    "title" : "Platform",
    "description" : `Software platforms are now essential drivers in both data science and cancer biology research, facilitating the analysis of the vast and complex datasets generated by modern research.
These platforms integrate diverse data types, including genomic sequencing, proteomics, and clinical trial results, enabling researchers to identify patterns and anomalies that would be impossible to detect through traditional methods`,
    "products" : [
      {
        "title" : "Caliper",
        "description": `CALIPER (Cancer Analysis and Learning with Integrated Processing, Evaluation and Reporting) is an AI-ready data platform designed to revolutionize precision oncology research by providing a structured framework for large-scale AI deployment. Recognizing the limitations of ad-hoc analysis, CALIPER offers a unified data model, based on FHIR, that tracks patient samples, assay results, and analysis methods, ensuring data and analytical coherence. It leverages deep learning-based methods to enable advanced functionalities, including labeling, multimodal search, embedding-based synthesis for cohort augmentation, and association via an integrated graph database. By projecting complex biological data into latent spaces, CALIPER facilitates cross-cohort integrated analysis and the development of predictive models. The platform includes a task orchestration system for automated deployment of machine learning workflows, a web-based user interface for queries and analysis, and tools for feature importance analysis and synthetic sample generation. CALIPER aims to bridge the gap between AI technology and clinical application through collaborations with projects like SMMART and Beat-AML, ultimately accelerating cancer research and enabling personalized medicine by providing an open-source, deployable system and a public-facing instance populated with open-access NCI data.`
      },{
        "title" : "FHIR Aggregator",
        "description": `FHIR Aggregator is a solution designed to streamline and accelerate integrative research by overcoming the significant barriers associated with identifying, accessing, and moving data across diverse NIH-funded resources. It provides a centralized, harmonized search interface that eliminates the need for researchers to manually query individual databases like dbGaP, AnVIL, and the Cancer Data Aggregator. By leveraging the FHIR standard and extending the Data Repository Service (DRS) specification, FHIR Aggregator enables researchers to efficiently discover potential samples and associated files, regardless of their location. Furthermore, it addresses the challenges of cloud interoperability by optimizing data access and minimizing costly cross-cloud data movement. As an integrated extension of existing infrastructure at NCI's CDA, ISB's Cancer Gateway, and NHGRI's AnVIL, FHIR Aggregator facilitates seamless data integration and promotes interoperability with international standards, ultimately empowering researchers to co-analyze data from multiple sources with greater ease and efficiency.`
      },{
        "title" : "BMEG",
        "description": `BMEG (BioMedical Evidence Graph) is a powerful graph database and query engine designed to facilitate the integrated analysis of diverse and complex cancer biology data. Unlike other biological data graphs, BMEG uniquely connects sample-level molecular and clinical information, such as RNA sequencing, mutation data, and drug response, to comprehensive reference knowledge bases, including pathway information and literature-derived associations. With over 41 million vertices and 57 million edges, BMEG offers a scalable platform accessible via a graph query-based API in Python, Javascript, and R, enabling researchers to perform sophisticated cross-dataset analyses, including mutation significance analysis, drug-response machine learning, and patient-level knowledge-base queries, ultimately accelerating discovery in cancer research.`
      }
    ]
  },{
    "title" : "Integration",
    "description" : "",
    "products" : [
      {
        "title" : "GRIP",
         "description": ""
      },
      {
        "title" : "Benchtop",
        "description": ""
      }
    ]
  },{
    "title":"Scalable Compute",
    "description" : "",
    "products" : [
      {
        "title":"Funnel", "description": ""
      },
      {"title":"tractor", "description": ""},
      {"title":"py-tes", "description": ""}
    ]
  },{
    "title" : "Data Normalization",
    "description" : "",
    "products": [
      {"title":"Sifter",  "description": ""},
      {"title":"JSONSchemaGraph",  "description": ""},
      {"title":"FHIRizer",  "description": ""},
      {"title":"Iceberg",  "description": ""},
    ]
  },{
    "title" : "AI",
    "description" : "",
    "products": [
      {"title":"SyntheVAEiser",  "description": ""},
      {"title":"EmbeddingKit",  "description": ""},
    ]
  }
]


const subjectPage = (sub:Subject) => {
    const [opened, { open, close }] = useDisclosure(false);
    var cards = sub.products.map( (x) => {
        return <Card>
            <Card.Section>{x.title}</Card.Section>
            <Card.Section>{x.description}</Card.Section>
        </Card>
    })
    return <div>
    <Button className='mt-5 w-md' onClick={open}>More info...</Button>
    <Modal opened={opened} onClose={close} size="100%" title={sub.title}>
        <SimpleGrid>
            {cards}
        </SimpleGrid>
    </Modal>
    </div>
}

export const Products = () => {
  const [rootRef, setRootRef] = useState<HTMLDivElement | null>(null);
  const [value, setValue] = useState<string | null>(subjects[0].title);
  const [controlsRefs, setControlsRefs] = useState<Record<string, HTMLButtonElement | null>>({});
  const setControlRef = (val: string) => (node: HTMLButtonElement) => {
    controlsRefs[val] = node;
    setControlsRefs(controlsRefs);
  };


  var tabTabs = subjects.map( (x) => {
    return <Tabs.Tab value={x.title} ref={setControlRef(x.title)} className="tab">
      {x.title}
    </Tabs.Tab>
  })

  var tabPanels = subjects.map( (x) => {
    var page = subjectPage(x)
    return <Tabs.Panel value={x.title}>
      <Card shadow="sm" padding="lg" radius="md" withBorder>
      <Card.Section>
      <Text fw={500}>{x.title}</Text>
      </Card.Section>
      {x.description}
      {page}
      </Card>
    </Tabs.Panel>
  })

  return (
        <div>
            <div className="max-w-7xl mx-auto my-7">
                <div className="text-left pb-8">
                <Text className="text-3xl font-extrabold text-gray-800 inline-block">
                    Products
                </Text>
            </div>
        </div>
        <div className="w-50 m-10">
            <Center>
              <Tabs variant="none" value={value} onChange={setValue} className="w-full">
                <Center>
                    <Tabs.List ref={setRootRef} className="list">
                    {tabTabs}
                    <FloatingIndicator
                        target={value ? controlsRefs[value] : null}
                        parent={rootRef}
                        className="indicator"
                    />
                    </Tabs.List>
                </Center>
                <Container fluid>
                {tabPanels}
                </Container>
              </Tabs>
            </Center>
          </div>
        </div>
  );
};

